### PR TITLE
Upgrade reason-react to 0.5.3 and bs-platform to 4.0.5

### PR DESCRIPTION
**Pull request by jihchi**
**[breaking change]**

Since both reason-react and bs-platform have new version, This PR is going to upgrade dependencies too, such that following warning messages won't appears on application which depends on re-formality:

```
   Warning number 3
   /home/jihchi/repos/<app>/node_modules/re-formality/src/Formality__PublicHelpers.re 8:14-
37

    6 ┆
    7 ┆ let toValueOnChange = event =>
    8 ┆   event |> ReactEventRe.Form.target |> targetValue;
    9 ┆
   10 ┆ let toValueOnBlur = event =>

   deprecated: ReactEventRe.Form.target
 Please use ReactEvent.Form.target and remove the surrounding ReactDOMRe.domElementToObj wrapper if any (no longer neede

   Warning number 3
   /home/jihchi/repos/<app>/node_modules/re-formality/src/Formality__PublicHelpers.re 11:14
-38

    9 ┆
   10 ┆ let toValueOnBlur = event =>
   11 ┆   event |> ReactEventRe.Focus.target |> targetValue;
   12 ┆
   13 ┆ let toCheckedOnChange = event =>

   deprecated: ReactEventRe.Focus.target
 Please use ReactEvent.Focus.target and remove the surrounding ReactDOMRe.domElementToObj wrapper if any (no longer need

   Warning number 3
   /home/jihchi/repos/<app>/node_modules/re-formality/src/Formality__PublicHelpers.re 14:14
-37
...
```

### CODE REVIEW

**Comment by alexfedoseev** [comment]
Awesome, thanks!

On the parcel bump: I faced this issue (https://github.com/parcel-bundler/parcel/issues/1638) some time ago, can you check if it's fixed in the recent version of parcel? You need to make production build and check if example doesn't throw in a browser on initial render.

**Comment by jihchi** [comment]
I've checked and no issue:

screenshot_2018-09-03_21-43-44_eu5m1
screenshot_2018-09-03_21-44-52_pt85n

**Comment by alexfedoseev** [comment]
Beautiful, thanks again!

**Comment by alexfedoseev** [comment]
@jihchi BTW I think your gh email is messed up and you don't show up in contributors list.

**Comment by jihchi** [comment]
@alexfedoseev oh! I didn't notice that. thank you for letting me know, I'll try to fix it.

**Pull request merged**
